### PR TITLE
add flask-compress and waitress as dependencies

### PR DESCRIPTION
**Pull request by janash**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by janash** [comment]
@paulsaxe - I wanted to get some experience with this, but I don't know what most of these things in the check list are talking about :)

**Review by paulsaxe — CHANGES_REQUESTED** [review]
Can you also change the version number and the hash? It should be
 
0c0f691289dc7ebfc877c1ee33499ebd38253e5ffdd0e551243d0d9c3a09ce92

(form PyPi)

**Comment by janash** [comment]
@paulsaxe - updated version number and hash

**Review by paulsaxe — APPROVED** [review]
perfect!

**Pull request merged**
